FROM ubuntu:focal
RUN mkdir /app
WORKDIR '/app'
RUN apt-get update
RUN apt-get install ca-certificates -y wget
RUN update-ca-certificates

RUN wget https://github.com/playit-cloud/playit-agent/releases/download/v0.15.12/playit-linux-armv7 /app/playit-linux-armv7

RUN chmod 0755 /app/playit-linux-armv7

CMD chmod 0755 /app/playit-linux-armv7
CMD /app/playit-linux-aarch64 -s
