#FROM ubuntu/focal:latest
FROM ubuntu:focal
RUN mkdir /app
WORKDIR '/app'
RUN apt-get update
RUN apt-get install ca-certificates -y
RUN update-ca-certificates


COPY playit-armv7 /app
#RUN chmod a+x playit-armv7
RUN chmod 0755 /app/playit-armv7
CMD /app/playit-armv7 -s
