#FROM ubuntu/focal:latest
FROM ubuntu:focal
RUN mkdir /app
WORKDIR '/app'
RUN apt-get update
RUN apt-get install ca-certificates -y
RUN update-ca-certificates



COPY playit-aarch64 /app


RUN chmod 0755 /app/playit-aarch64
CMD /app/playit-aarch64 -s
