name: Build develop image

on: 
  push:
      branches:
      - 'v.0.9.3'


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  build:
    name: Build container -arm
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Update Readme.md and description
      uses: meeDamian/sync-readme@v1.0.6
      with:
        user: ${{ secrets.DOCKER_USERNAME }}
        pass: ${{ secrets.DOCKER_PASSWORD }}
        slug: pepaondrugs/playitgg-docker
        readme: ./README.md
        description: full docs at github
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with: 
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and push
      uses: docker/build-push-action@v3
      with: 
        context: .
        platforms: linux/arm64
        file: ./Dockerfile-arm
        push: true
        tags: pepaondrugs/playitgg-docker:v0.9.3-arm
