name: Check and Build Playit Docker Image Armv7

on:
  schedule:
    - cron: "0 * * * *" # every hour
  workflow_dispatch:     # manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get latest Playit release version
        id: get_release
        run: |
          LATEST=$(curl -s https://api.github.com/repos/playit-cloud/playit-agent/releases/latest | jq -r .tag_name)
          echo "latest=$LATEST" >> $GITHUB_OUTPUT

      - name: Print latest version
        run: |
          echo "Latest Playit release found: ${{ steps.get_release.outputs.latest }}"

      - name: Determine if build is needed
        id: check_dockerhub
        run: |
          IMAGE="pepaondrugs/playitgg-docker"
          VERSION="${{ steps.get_release.outputs.latest }}-armv7"
          STATUS=$(curl -s -o /dev/null -w "%{http_code}" "https://hub.docker.com/v2/repositories/$IMAGE/tags/$VERSION/")
          
          if [ "$STATUS" -eq 200 ]; then
            echo "needs_build=false" >> "$GITHUB_OUTPUT"
          else
            echo "needs_build=true" >> "$GITHUB_OUTPUT"
          fi



      - name: Stop if already built
        if: ${{ steps.check_dockerhub.outputs.needs_build == 'false' }}
        run: echo "Docker image already exists — skipping build."

      - name: Set up QEMU
        if: ${{ steps.check_dockerhub.outputs.needs_build == 'true' }}
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        if: ${{ steps.check_dockerhub.outputs.needs_build == 'true' }}
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        if: ${{ steps.check_dockerhub.outputs.needs_build == 'true' }}
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        if: ${{ steps.check_dockerhub.outputs.needs_build == 'true' }}
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64,linux/ppc64le
          file: ./Dockerfile-armv7
          push: true
          build-args: |
            PLAYIT_VERSION=${{ steps.get_release.outputs.latest }}
          tags: |
            pepaondrugs/playitgg-docker:${{ steps.get_release.outputs.latest }}-armv7
            pepaondrugs/playitgg-docker:armv7

