name: Build and push

on: 
  push:
      branches:
      - 'master'
  schedule:
  - cron: "0 */12 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  build:
    name: Build container
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Update Readme.md and description
      uses: meeDamian/sync-readme@v1.0.6
      with:
        user: ${{ secrets.DOCKER_HUB_USERNAME }}
        pass: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        slug: pepaondrugs/minecraft-paper-server
        readme: ./README.md
        description: Minecraft Java Server 1.19+ — Starts fast, runs stable and is always up-to-date.
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with: 
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v3
      with: 
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
