name: Build Playit Docker Image

on:
  workflow_dispatch:
    inputs:
      playit_version:
        description: "Playit version to build (e.g., v0.16.2)"
        required: true

jobs:
  build:
    name: Build container
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Update Readme.md and description
      uses: meeDamian/sync-readme@v1.0.6
      with:
        user: ${{ secrets.DOCKER_USERNAME }}
        pass: ${{ secrets.DOCKER_PASSWORD }}
        slug: pepaondrugs/playitgg-docker
        readme: ./README.md
        description: Playit.gg as a Docker image — code:https://github.com/PepaonDrugs/playitgg-docker

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        platforms: linux/amd64,linux/ppc64le
        file: ./Dockerfile
        push: true
        build-args: |
          PLAYIT_VERSION=${{ github.event.inputs.playit_version }}
        tags: |
          pepaondrugs/playitgg-docker:${{ github.event.inputs.playit_version }}
          pepaondrugs/playitgg-docker:latest

